### PR TITLE
New entrance screen + straight to devices

### PR DESCRIPTION
**Pull request by MarcF12**
This is not yet finished. There should be better integration with auth0, but I have difficulty of merging @Mikmist 's code in this branch, because it's says that there a not commits to bring in (from the auth0 branch), maybe you can have a look at it?

### CODE REVIEW

**Comment by Mikmist** [comment]
Why are you merging to development, wasn't this branch created off of feature/auto0?

**Comment by MarcF12** [comment]
Euh I think I merged the commits from that branch in this one. But I cannot see them

**Comment by Mikmist** [comment]
I can see some of the commits of the auth0. I'll try and see what I can do.

**Comment by Mikmist** [comment]
I see you rebased development into this, which makes it kind of hard to make a pr back into feature/auth0. But I think that merging auth0 into this branch will revert changes that we do not want.

**Pull request merged**
