### PR TITLE
Added time-track + Modified Architectural Document + E-mail info for …

### PR DESCRIPTION
**Pull request by BuzzDeejayLord**
I have added my modifications to the architectural document and the e-mail credentials for future teams.

### CODE REVIEW

**Comment by MarcF12** [comment]
@daangroot @Mikmist  What do you think?

**Comment by Mikmist** [comment]
I agree

**Comment by daangroot** [comment]
I agree as well, the password shouldn't be in this repo.

**Comment by BuzzDeejayLord** [comment]
And where do you all propose to put it guys? Because you didn't give me any solution

**Comment by daangroot** [comment]
In the google drive.

**Pull request merged**
